// game.js
export const SET_GAME_USER = "SET_GAME_USER";
export const SET_GAME_LOGINUSER = "SET_GAME_LOGINUSER";
export const SET_GAME_ACCESSTOKEN = "SET_GAME_ACCESSTOKEN";
export const SET_GAME_LANGUAGE = "SET_GAME_LANGUAGE";
export const SET_GAME_LOCALE = "SET_GAME_LOCALE";
export const SET_GAME_EXPIRESIN = "SET_GAME_EXPIRESIN";
export const SET_GAME_EXPIRYDATE = "SET_GAME_EXPIRYDATE";
export const SET_PLANET_ID = "SET_PLANET_ID";
export const SET_PLANET_NAME = "SET_PLANET_NAME";
export const SET_PLANET_POSX = "SET_PLANET_POSX";
export const SET_PLANET_POSY = "SET_PLANET_POSY";
export const SET_PLANET_LIST = "SET_PLANET_LIST";
export const SET_MAPS_PLANETS = "SET_MAPS_PLANETS";
export const SET_MAPS_LASTUPDATE = "SET_MAPS_LASTUPDATE";
